name: PHP Composer

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: "php: ${{ matrix.php }} TYPO3: ${{ matrix.typo3 }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        php: [ '82', '83', '84', '85' ]
        typo3: [ '13', '14' ]
    outputs:
      result: ${{ steps.set-result.outputs.result }}
      php: ${{ matrix.php }}
      typo3: ${{ matrix.typo3 }}
    container:
      image: ghcr.io/typo3/core-testing-php${{ matrix.php }}:latest
    steps:
      - name: Install Node.js (Alpine)
        run: apk add --no-cache nodejs npm
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            vendor
            node_modules
          key: ${{ matrix.typo3 }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ matrix.typo3 }}-${{ matrix.php }}-composer-
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - run: composer update --with typo3/minimal:^${{ matrix.typo3 }} --ignore-platform-req=php+
      - run: ./vendor/bin/grumphp run --ansi --no-interaction
      - run: composer test
